spring.application.name=servicehub

# ? DATABASE (from Render ENV)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ? REMOVE this (Hibernate auto-detects)
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# ? SERVER PORT (Render requirement)
server.port=${PORT:8080}

# ================= SECURITY =================

# JWT
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=86400000

# ================= MAIL =================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ================= FILE =================

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.upload.dir=uploads/

# ================= CASHFREE =================

cashfree.app.id=${CASHFREE_APP_ID}
cashfree.secret.key=${CASHFREE_SECRET_KEY}
cashfree.api.version=2023-08-01
cashfree.base.url=https://sandbox.cashfree.com/pg

# ================= FRONTEND =================

app.base-url=${APP_BASE_URL}


spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.auto-commit=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
spring.jpa.properties.hibernate.jdbc.use_streams_for_lob=true